### ISSUE TITLE
config is loaded twice

### ISSUE THREAD

**Issue by grosser** [spox/bogo-config#6]
this is bad because it is slow and does whatever is done in .sfn twice ... which in our case means doing the same work twice which lead to a bug

once when initializing the config:

```
vendor/bundle/gems/bogo-config-0.2.2/lib/bogo-config/config.rb:297:in `instance_eval'
vendor/bundle/gems/bogo-config-0.2.2/lib/bogo-config/config.rb:297:in `struct_load'
vendor/bundle/gems/bogo-config-0.2.2/lib/bogo-config/config.rb:203:in `load_file'
vendor/bundle/gems/bogo-config-0.2.2/lib/bogo-config/config.rb:178:in `load!'
vendor/bundle/gems/bogo-config-0.2.2/lib/bogo-config/config.rb:138:in `init!'
vendor/bundle/gems/bogo-config-0.2.2/lib/bogo-config/config.rb:114:in `initialize'
```

and once when actually loading the config after:

```
vendor/bundle/gems/bogo-config-0.2.2/lib/bogo-config/config.rb:203:in `load_file'
vendor/bundle/gems/bogo-config-0.2.2/lib/bogo-config/config.rb:178:in `load!'
vendor/bundle/gems/bogo-cli-0.2.8/lib/bogo-cli/command.rb:103:in `load_config!'
vendor/bundle/gems/bogo-cli-0.2.8/lib/bogo-cli/command.rb:36:in `initialize'
vendor/bundle/gems/sfn-3.0.18/lib/sfn/command.rb:51:in `initialize'
```

@chrisroberts

**Comment by grosser** [comment]
FYI workaround:

```
# .sfn.rb
$dot_sfn_loaded ||= begin # https://github.com/spox/bogo-config/issues/6
   ... put all the config here ...
end
```

**Comment by chrisroberts** [comment]
Fix is applied within bogo-cli as of version 0.2.10. Thanks for the report!
